Add option to disable container resolver
Signed-off-by: Boris HUISGEN <boris@foobot.io>

diff --git a/alpine-base/rootfs/etc/cont-init.d/01-resolver b/alpine-base/rootfs/etc/cont-init.d/01-resolver
--- a/alpine-base/rootfs/etc/cont-init.d/01-resolver
+++ b/alpine-base/rootfs/etc/cont-init.d/01-resolver
@@ -13,6 +13,10 @@ if [ ${links} -gt 1 ]; then
     fi
 
     case "${CONTAINER_RESOLVER}" in
+        disable)
+            exit 0
+            ;;
+
         interface)
             if [ -z "${CONTAINER_RESOLVER_INTERFACENAME}" ]; then
                 CONTAINER_RESOLVER_INTERFACENAME=eth0
@@ -23,17 +27,20 @@ if [ ${links} -gt 1 ]; then
             fi
 
             CONTAINER_IP=$(ip -o addr show ${CONTAINER_RESOLVER_INTERFACENAME}|grep "${CONTAINER_RESOLVER_INTERFACETYPE} "|awk '{ print $4; }'|sed -e 's/\/.*$//')
+            if [ -z "${CONTAINER_IP}" ]; then
+                echo "Failed to get IP address, aborting" >&2
+                exit 2
+            fi
             ;;
 
         route)
             CONTAINER_IP=$(ip route get 1|awk '{ print $NF; exit; }')
+            if [ -z "${CONTAINER_IP}" ]; then
+                echo "Failed to get IP address, aborting" >&2
+                exit 2
+            fi
             ;;
     esac
-
-    if [ -z "${CONTAINER_IP}" ]; then
-        echo "Failed to get IP address, aborting" >&2
-        exit 2
-    fi
 
     export CONTAINER_HOST
     export CONTAINER_IP
