Force env variables creation
Signed-off-by: Boris HUISGEN <boris@foobot.io>

diff --git a/alpine-base/rootfs/etc/cont-init.d/01-resolver b/alpine-base/rootfs/etc/cont-init.d/01-resolver
--- a/alpine-base/rootfs/etc/cont-init.d/01-resolver
+++ b/alpine-base/rootfs/etc/cont-init.d/01-resolver
@@ -1,9 +1,5 @@
 #!/usr/bin/with-contenv sh
 
-if [ -z "${CONTAINER_RESOLVER}" ] || [ "${CONTAINER_RESOLVER}" == "disable" ]; then
-    exit 0
-fi
-
 links=$(ip -o link show|wc -l)
 if [ ${links} -gt 1 ]; then
     CONTAINER_HOST=$(cat /etc/hostname)
@@ -27,17 +23,22 @@ if [ ${links} -gt 1 ]; then
             fi
 
             CONTAINER_IP=$(ip -o addr show "${CONTAINER_RESOLVER_INTERFACENAME}"|grep "${CONTAINER_RESOLVER_INTERFACETYPE} "|awk '{ print $4; }'|sed -e 's/\/.*$//')
+
+            if [ -z "${CONTAINER_IP}" ]; then
+                echo "Failed to get IP address, aborting" >&2
+                exit 2
+            fi
             ;;
 
         route)
             CONTAINER_IP=$(ip route get 1|awk '{ print $NF; exit; }')
+
+            if [ -z "${CONTAINER_IP}" ]; then
+                echo "Failed to get IP address, aborting" >&2
+                exit 2
+            fi
             ;;
     esac
-
-    if [ -z "${CONTAINER_IP}" ]; then
-        echo "Failed to get IP address, aborting" >&2
-        exit 2
-    fi
 
     export CONTAINER_HOST
     export CONTAINER_IP
