Refactor messages + exit values

diff --git a/alpine-base-consul/rootfs/etc/cont-init.d/02-consul b/alpine-base-consul/rootfs/etc/cont-init.d/02-consul
--- a/alpine-base-consul/rootfs/etc/cont-init.d/02-consul
+++ b/alpine-base-consul/rootfs/etc/cont-init.d/02-consul
@@ -54,7 +54,8 @@ if [ ! -z ${CONSUL_SERVICENAME} ] && [ -z ${CONSUL_SERVICEADDR} ]; then
     esac
 
     if [ -z ${CONSUL_SERVICEADDR} ]; then
-        exit 2
+        echo "Failed to resolve service address, aborting" >&2
+        exit 1
     fi
 
     export CONSUL_SERVICEADDR
diff --git a/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb b/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb
--- a/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb
+++ b/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb
@@ -9,7 +9,7 @@ if [ -z ${MARIADB_CONFIG} ]; then
         fi
 
         if [ ! -f "/usr/share/mysql/${MARIADB_PROFILE}.cnf" ]; then
-            echo "Configuration profile has not been found, aborting"
+            echo "Configuration profile has not been found, aborting" >&2
             exit 1
         fi
 
@@ -25,8 +25,8 @@ if [ -z ${MARIADB_CONFIG} ]; then
         sleep 4
 
         if [ -z ${MARIADB_ROOTPASSWORD} ]; then
-            echo "MARIADB_ROOTPASSWORD is not set, aborting"
-            exit 1
+            echo "MARIADB_ROOTPASSWORD is not set, aborting" >&2
+            exit 2
         fi
 
         mysql -u root -e " \
