Refactor init/finish scripts

diff --git a/alpine-base-consul/rootfs/etc/cont-init.d/02-consul b/alpine-base-consul/rootfs/etc/cont-init.d/02-consul
--- a/alpine-base-consul/rootfs/etc/cont-init.d/02-consul
+++ b/alpine-base-consul/rootfs/etc/cont-init.d/02-consul
@@ -25,7 +25,7 @@ if [ -z ${CONSUL_KEYPREFIX} ]; then
     printf "%s" "${CONSUL_KEYPREFIX}" > /var/run/s6/container_environment/CONSUL_KEYPREFIX
 fi
 
-if [ ! -z ${CONSUL_SERVICENAME} ]; then
+if [ ! -z ${CONSUL_AGENT} ] && [ ! -z ${CONSUL_SERVICENAME} ]; then
     if [ -z ${CONSUL_RESOLVER} ]; then
         CONSUL_RESOLVER=container
     fi
@@ -47,14 +47,13 @@ if [ ! -z ${CONSUL_SERVICENAME} ]; then
             CONSUL_SERVICEADDR=$(ip -o addr show ${CONSUL_RESOLVER_INTERFACENAME}|grep "${CONSUL_RESOLVER_INTERFACETYPE} "|awk '{ print $4; }'|sed -e 's/\/.*$//')
             ;;
 
-
         route)
             CONSUL_SERVICEADDR=$(ip route get 1|awk '{ print $NF; exit; }')
             ;;
     esac
 
     if [ -z ${CONSUL_SERVICEADDR} ]; then
-        echo "Failed to resolve service address, aborting" >&2
+        echo "Failed to resolve consul service address, aborting" >&2
         exit 1
     fi
 
