Refactor consul wait-for
Signed-off-by: Boris HUISGEN <bhuisgen@hbis.fr>

diff --git a/alpine-base-consul/rootfs/etc/cont-init.d/04-cont-consul b/alpine-base-consul/rootfs/etc/cont-init.d/04-cont-consul
--- a/alpine-base-consul/rootfs/etc/cont-init.d/04-cont-consul
+++ b/alpine-base-consul/rootfs/etc/cont-init.d/04-cont-consul
@@ -1,6 +1,12 @@
 #!/usr/bin/with-contenv sh
 
 if [ ! -z "${CONSUL_AGENT}" ]; then
+    echo "==> Waiting for service"
+
+    if ! /etc/cont-consul/wait-for; then
+        echo "Failed to wait for service, aborting" >&2 && exit 1
+    fi
+
     echo "==> Generating container configuration"
 
     if ! consul-template -config /etc/cont-consul/conf.d/config.hcl -once; then
diff --git a/alpine-base-consul/rootfs/etc/cont-init.d/98-cont-consul b/alpine-base-consul/rootfs/etc/cont-init.d/98-cont-consul
--- a/alpine-base-consul/rootfs/etc/cont-init.d/98-cont-consul
+++ b/alpine-base-consul/rootfs/etc/cont-init.d/98-cont-consul
@@ -3,7 +3,8 @@
 if [ ! -z "${CONSUL_AGENT}" ]; then
     echo "==> Registering container services/checks"
 
-    /etc/cont-consul/register || (
-        echo "Failed to register container services/checks, aborting" >&2 && exit 1
-    )
+    if ! /etc/cont-consul/register; then
+        echo "Failed to register container services/checks, aborting" >&2
+        exit 1
+    fi
 fi
