Break init when custom config script failed

diff --git a/alpine-consul/rootfs/etc/cont-init.d/10-consul b/alpine-consul/rootfs/etc/cont-init.d/10-consul
--- a/alpine-consul/rootfs/etc/cont-init.d/10-consul
+++ b/alpine-consul/rootfs/etc/cont-init.d/10-consul
@@ -13,6 +13,10 @@ if [ -z ${CONSUL_CONFIG} ]; then
         echo "==> Configuring consul from script"
 
         /bin/sh ${CONSUL_CONFIGSCRIPT}
+        if [ $? -ne 0 ]; then
+            echo "Failed to configure from script, aborting" >&2
+            exit 2
+        fi
     fi
 
     export CONSUL_CONFIG=1
diff --git a/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb b/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb
--- a/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb
+++ b/alpine-mariadb/rootfs/etc/cont-init.d/10-mariadb
@@ -58,6 +58,10 @@ if [ -z ${MARIADB_CONFIG} ]; then
         echo "==> Configuring mariadb from script"
 
         /bin/sh ${MARIADB_CONFIGSCRIPT} ${MARIADB_ROOTPASSWORD}
+        if [ $? -ne 0 ]; then
+            echo "Failed to configure from script, aborting" >&2
+            exit 3
+        fi
     fi
 
     export MARIADB_CONFIG=1
