Refactor service scripts
Signed-off-by: Boris HUISGEN <boris@foobot.io>

diff --git a/alpine-consul/rootfs/etc/cont-init.d/10-consul b/alpine-consul/rootfs/etc/cont-init.d/10-consul
--- a/alpine-consul/rootfs/etc/cont-init.d/10-consul
+++ b/alpine-consul/rootfs/etc/cont-init.d/10-consul
@@ -1,11 +1,11 @@
 #!/usr/bin/with-contenv sh
 
 if [ ! -f /var/lib/consul/config ]; then
-    echo "==> Configuring consul from environment"
+    echo "==> Configuring consul"
 
     consul-template -config /etc/consul-template/conf-env.d -once
     if [ $? -ne 0 ]; then
-        echo "Failed to configure from environment, aborting" >&2
+        echo "Failed to configure, aborting" >&2
         exit 1
     fi
 
diff --git a/alpine-nomad/rootfs/etc/cont-init.d/10-nomad b/alpine-nomad/rootfs/etc/cont-init.d/10-nomad
--- a/alpine-nomad/rootfs/etc/cont-init.d/10-nomad
+++ b/alpine-nomad/rootfs/etc/cont-init.d/10-nomad
@@ -1,7 +1,7 @@
 #!/usr/bin/with-contenv sh
 
 if [ ! -f /var/lib/nomad/config ]; then
-    echo "==> Configuring nomad from environment"
+    echo "==> Configuring nomad"
 
     if [ -S /var/run/docker.sock ]; then
         GID=$(stat -c "%g" /var/run/docker.sock)
@@ -17,7 +17,7 @@ if [ ! -f /var/lib/nomad/config ]; then
 
     consul-template -config /etc/consul-template/conf-env.d -once
     if [ $? -ne 0 ]; then
-        echo "Failed to configure from environment, aborting" >&2
+        echo "Failed to configure, aborting" >&2
         exit 1
     fi
 
